version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
        - "minor"
        - "patch"
      major:
        update-types:
        - "major"
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
        - "minor"
        - "patch"
      major:
        update-types:
        - "major"
