services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1234'

  api:
    build: 
      context: ./api
    command: "./django-test-entrypoint.sh"
    environment:
      - DJANGO_SETTINGS_MODULE=nvdnew.settings.dev
    depends_on:
      - postgres
    volumes:
      - ./api:/api
