# Generated by Django 2.1.1 on 2018-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_name', models.CharField(max_length=250)),
                ('listing_company_name', models.CharField(max_length=250)),
            ],
        ),
    ]
