# Generated by Django 2.1.1 on 2018-09-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_company_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_name',
            new_name='name',
        ),
    ]
