# Generated by Django 2.1.3 on 2018-11-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0002_auto_20180922_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deadline',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
