# Generated by Django 2.1.3 on 2018-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0004_listing_logo_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Sommerjobb', 'Sommerjobb'), ('Fast stilling', 'Fast stilling'), ('Deltidsstilling', 'Deltidsstilling'), ('Internship', 'Internship'), ('Trainee', 'Trainee'), ('Annet', 'Annet')], default='Annet', max_length=250),
        ),
    ]
