# Generated by Django 2.1.3 on 2018-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0005_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_url',
            field=models.CharField(default='zombo.com', max_length=250),
            preserve_default=False,
        ),
    ]
