# Generated by Django 2.1.3 on 2018-11-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0006_listing_listing_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('logo_uri', models.CharField(max_length=250)),
                ('website_url', models.CharField(max_length=250)),
            ],
        ),
    ]
