# Generated by Django 2.1.5 on 2019-01-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0008_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
