# Generated by Django 2.1.5 on 2019-01-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0010_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='level',
            field=models.CharField(choices=[('Gull', 'Gull'), ('Sølv', 'Sølv'), ('Bronse', 'Bronse')], default='Gull', max_length=250),
        ),
    ]
