# Generated by Django 2.1.5 on 2019-01-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0011_business_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
