# Generated by Django 2.2.4 on 2019-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0012_auto_20190116_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
