# Generated by Django 2.2.4 on 2019-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0012_auto_20190116_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_url', models.CharField(max_length=250)),
                ('internal_url', models.CharField(max_length=250)),
                ('iframe_height', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='level',
            field=models.CharField(choices=[('Hovedsamarbeidspartner', 'Hovedsamarbeidspartner'), ('Samarbeidspartner', 'Samarbeidspartner'), ('Gull', 'Gull'), ('Sølv', 'Sølv'), ('Bronse', 'Bronse')], default='Gull', max_length=250),
        ),
    ]
