# Generated by Django 2.2.4 on 2019-11-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0013_auto_20191103_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='text',
        ),
    ]
