# Generated by Django 2.2.4 on 2020-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0014_remove_sponsor_text'),
        ('nvdagen', '0013_auto_20191215_1638'),
    ]

    operations = [
    ]
