# Generated by Django 2.2.4 on 2020-01-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0015_merge_20200121_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='days',
            field=models.CharField(choices=[('Ingen dager', 'Ingen dager'), ('Dag 1', 'Dag 1'), ('Dag 2', 'Dag 2'), ('Begge dager', 'Begge dager')], default='Ingen dager', max_length=250),
        ),
        migrations.AlterField(
            model_name='business',
            name='text',
            field=models.TextField(),
        ),
    ]
