# Generated by Django 2.2.4 on 2020-01-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0016_auto_20200121_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='internal_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
