# Generated by Django 2.2.12 on 2021-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0017_auto_20200123_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('timeStart', models.IntegerField()),
                ('timeEnd', models.IntegerField()),
                ('paragraph', models.CharField(max_length=10000)),
                ('registration', models.BooleanField(default=False)),
                ('maxRegistered', models.IntegerField(blank=True, null=True)),
                ('registered', models.IntegerField(blank=True, null=True)),
                ('cancelEmail', models.CharField(blank=True, max_length=250, null=True)),
                ('registrationStart', models.IntegerField(blank=True, null=True)),
                ('registrationEnd', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo_uri',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
