# Generated by Django 2.2.12 on 2021-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0018_auto_20210118_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='paragraph',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='timeEnd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
