# Generated by Django 2.2.12 on 2021-01-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0021_auto_20210120_1642'),
        ('nvdagen', '0018_auto_20201113_1035'),
    ]

    operations = [
    ]
