# Generated by Django 2.2.24 on 2021-10-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0023_auto_20210122_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='code',
            field=models.CharField(default='superkode', max_length=250),
            preserve_default=False,
        ),
    ]
