# Generated by Django 2.2.26 on 2022-01-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0025_auto_20220129_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='registered',
        ),
    ]
