# Generated by Django 2.2.28 on 2023-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0026_remove_program_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='standpos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='standpos_y',
            field=models.IntegerField(default=0),
        ),
    ]
