# Generated by Django 2.2.28 on 2023-10-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0026_remove_program_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinTheWheel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
