# Generated by Django 2.2.28 on 2023-10-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0027_spinthewheel'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinthewheel',
            name='business',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='nvdagen.Business'),
            preserve_default=False,
        ),
    ]
