# Generated by Django 2.2.28 on 2023-10-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0028_auto_20231018_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='standpos',
            new_name='standnumber',
        ),
    ]
