# Generated by Django 2.2.28 on 2023-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0029_auto_20231018_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='standnumber',
            field=models.IntegerField(default=10),
        ),
    ]
