# Generated by Django 2.2.28 on 2025-09-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0030_auto_20231018_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
