# Generated by Django 2.2.28 on 2025-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0030_auto_20231018_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infobox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('paragraph', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
