# Generated by Django 2.2.28 on 2025-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0031_participant_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='allergies',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
