# Generated by Django 2.2.28 on 2025-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0032_auto_20250927_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
