# Generated by Django 2.2.28 on 2025-09-28 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0033_auto_20250927_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='attendance_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
