# Generated by Django 2.2.28 on 2025-09-28 22:43

from django.db import migrations, models
import uuid


def generate_unique_tokens(apps, schema_editor):
    Participant = apps.get_model('nvdagen', 'Participant')
    for participant in Participant.objects.all():
        participant.attendance_token = uuid.uuid4()
        participant.save(update_fields=['attendance_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0033_auto_20250927_1126'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='participant',
            name='attendance_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Generate unique tokens for existing rows
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='participant',
            name='attendance_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
