# Generated by Django 2.2.28 on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0033_auto_20250927_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('Hovedsponsor', 'Hovedsponsor'), ('Kaffesponsor', 'Kaffesponsor'), ('Annen sponsor', 'Annen sponsor')], default='Annen sponsor', max_length=250),
        ),
    ]
