# Generated by Django 2.2.28 on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0034_sponsor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=50, default=''),
            preserve_default=False,
        ),
    ]
