# Generated by Django 2.2.28 on 2026-01-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0034_auto_20250928_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qr_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
