# Generated by Django 2.2.28 on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0035_participant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='allowDeregistration',
            field=models.BooleanField(default=True),
        ),
    ]
