# Generated by Django 2.2.28 on 2026-01-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0031_infobox'),
        ('nvdagen', '0036_program_allowderegistration'),
    ]

    operations = [
    ]
