# Generated by Django 2.2.28 on 2026-01-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0036_program_allowderegistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_nb', models.CharField(max_length=10000)),
                ('question_en', models.CharField(max_length=10000)),
                ('answer_nb', models.CharField(max_length=10000)),
                ('answer_en', models.CharField(max_length=10000)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='level',
            field=models.CharField(choices=[('Hovedsamarbeidspartner', 'Hovedsamarbeidspartner'), ('Samarbeidspartner', 'Samarbeidspartner'), ('Gull', 'Gull'), ('Sølv', 'Sølv'), ('Bronse', 'Bronse'), ('Startup', 'Startup')], default='Gull', max_length=250),
        ),
    ]
