# Generated by Django 2.2.28 on 2026-01-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0037_merge_20260121_1314'),
        ('nvdagen', '0037_auto_20260121_1253'),
    ]

    operations = [
    ]
