# Generated by Django 2.2.28 on 2026-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0038_merge_20260121_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infobox',
            old_name='paragraph',
            new_name='paragraph_en',
        ),
        migrations.RemoveField(
            model_name='infobox',
            name='title',
        ),
        migrations.AddField(
            model_name='infobox',
            name='paragraph_nb',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='infobox',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='infobox',
            name='title_nb',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
