# Generated by Django 2.2.28 on 2026-01-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0039_auto_20260122_1505'),
        ('nvdagen', '0035_add_qr_email_sent'),
    ]

    operations = [
    ]
