# Generated by Django 2.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvdagen', '0040_merge_20260125_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pdf_uri',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
